### ISSUE TITLE
[FIXED] Erros em 2 Eventos

### ISSUE THREAD

**Issue by SkelletonX** [gabrizord/HEventosReloaded#1]
Quando inicia o fight: https://pastebin.com/7wUw3zNA

Quando inicia o Killer: https://pastebin.com/P3Gv92ea

os 2 erros parece ser o mesmo!
ainda n abri a source mas o erro parece estar um Listener

**Comment by gabrizord** [comment]
Obrigado por reportar, vou refazer o sistema de register listener

**Comment by gabrizord** [comment]
por hora foi resolvido!

**Comment by SkelletonX** [comment]
eu tinha fixado com, eu disse porem n consegui mandar para você o commit
